# Generated by Django 5.1.1 on 2024-09-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('Id_Propuesta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Area', models.CharField(choices=[('GR', 'Geología y Recursos Minerales'), ('MI', 'Minería')], max_length=2)),
                ('Categoria', models.CharField(choices=[('SCR', 'Scipt'), ('AUT', 'Automatización'), ('LIB', 'Librería'), ('APP', 'Aplicación interactiva'), ('IAR', 'Inteligencia artificial'), ('MET', 'Metodología')], max_length=3)),
                ('Proyecto', models.CharField(max_length=100)),
                ('Encargado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desarrollador', models.CharField(max_length=100)),
                ('Horas_Presupuestadas', models.IntegerField()),
                ('Id_Propuesta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='propuestas.propuesta')),
            ],
        ),
    ]
