# Generated by Django 5.1.1 on 2024-09-30 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horas',
            new_name='Hora',
        ),
        migrations.AddField(
            model_name='propuesta',
            name='Correo',
            field=models.EmailField(default='NaN', max_length=20, validators=[django.core.validators.EmailValidator(allowlist=['srk.com'])]),
        ),
    ]
